telegram:
  token: env
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
  useCustomEmojiFilter: false
  replaceAtWithHash: false
  replaceExcessiveSpaces: false
  removeNewlineSpaces: false
  suppressFileTooBigMessages: false
  suppressThisIsPrivateBotMessage: false

discord:
  useNickname: true
  token: env
  skipOldMessages: true
  replyLength: 100
  maxReplyLines: 2
  suppressThisIsPrivateBotMessage: true
  enableCustomStatus: false
  customStatusMessage: "TediCross"

bridges:
  - name: Magic War Telegram
    direction: both

    telegram:
      chatId: -1003867877823
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnDiscord: true

    discord:
      channelId: '1551748946072838175'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
      disableWebPreviewOnTelegram: false
      useEmbeds: 'auto'

debug: false
messageTimeoutAmount: 24
messageTimeoutUnit: 'hours'
persistentMessageMap: false
